### ISSUE TITLE
Cant change prepayment clearing_bank_account data in invoice document

### ISSUE THREAD

**Issue by dmmm777** [PAYONE-GmbH/shopware-6#110]
I am not able to change customFields.payone_clearing_bank_account data for the invoice document.
It is used here https://github.com/PAYONE-GmbH/shopware-6/blob/0b85922a40257a9fdc543fccc2db48acad80441f/src/Resources/views/documents/invoice.html.twig#L45

> Kontoinhaber: Test Nutzer
IBAN: DE00123456782599100003
BIC: TESTTEST
Verwendungszweck: 544153452

How can i change this. I found the current data in "SettingsController.php" but it shouldnt be changed there.
Any hints?

We are working with SW 6.4.1.0 and PayOne 2.2.0

**Comment by hreinberger** [comment]
Hi @jvarelmann can you take a look?

**Comment by jvarelmann** [comment]
hello,

why do you want to change this ? if you using PayonePrepayment Payone will deliver the clearing data via API , if you want to use your own bank account in the invoice use the invoice plugin from shopware. The Payone invoice function is to use when Payone shall handle the invoice 

regards Juergen
