### ISSUE TITLE
Shopware 6.4.2 Support

### ISSUE THREAD

**Issue by fgiering** [PAYONE-GmbH/shopware-6#114]
Moin.
Can you give us a hint how long it will take to serve the 6.4.2 Support of the Plugin?
We planed to upgrade this week to 6.4.2 as we sadly just recognized, that only 6.4.1 is supported...

**Comment by axe1987** [comment]
Any updates on this issue?

**Comment by hreinberger** [comment]
Hi there, unfortunately Shopware 6.4.2 broke our SEPA Direct Debit flow. We're currently working on it, along with a massive refactoring of our plugin, which is why 6.4.2/3 compatibility can take a little longer :( We'll at least tag a beta release as soon as we can.

**Comment by fgiering** [comment]
Can you tell roughly what "a little longer" means to you? Is it days, is it weeks, is it months?

**Comment by hreinberger** [comment]
We're hoping to be able to tag a beta next week.

**Comment by axe1987** [comment]
Are there any news? Updates?

**Comment by Nik-1909** [comment]
Hello,

can we get an update on when we can expect at least a beta?

Shopware 6.4.2 was released on 07/07 - that's now 7 weeks ago and the Payone plugin is still not compatible.

We expected more from the self-proclaimed number 1 payment service provider ...

**Comment by fgiering** [comment]
There is something cooking: https://github.com/PAYONE-GmbH/shopware-6/commit/518d8d0f86411d602bdd075a722a76718d5c8815

**Comment by axe1987** [comment]
Nice thanks...
I will try it todoay/tomorrow.

**Comment by hreinberger** [comment]
Rejoice! We've just tagged 2.3.0-beta.1: https://github.com/PAYONE-GmbH/shopware-6/releases/tag/v2.3.0-beta.1 

We're running some additional tests in the following days and will release the new version in the Shopware Store this week.

Also, please accept my apologies for lagging behind on compatibility with new shopware versions. We're working hard on better keeping up with Shopware's release cadence.

**Comment by axe1987** [comment]
Trying your beta I get the following error when trying to use "Rechnungskauf"

/account/order/edit/{{UUID}}?error-code=CHECKOUT__SYNC_PAYMENT_PROCESS_INTERRUPTED

Any Ideas

**Comment by hreinberger** [comment]
Hi @jvarelmann we saw no problems testing Paysafe Invoice, right? Could you investigate? And @axe1987 how did you install the new beta?

**Comment by axe1987** [comment]
> Hi @jvarelmann we saw no problems testing Paysafe Invoice, right? Could you investigate? And @axe1987 how did you install the new beta?

I downloaded you tagged beta as zip and uploaded it via the admin area upload button.
Then I was able to press the "Aktualisieren" btn

**Comment by jvarelmann** [comment]
Hello 
no we didn´t see any problems with Paysafe Invoice. Try to deinstall the plugin clear all caches and reinstall it again, clear and rewarm the cache again

**Comment by axe1987** [comment]
Will try

**Comment by axe1987** [comment]
couldn't resolve the issue after uninstall / reinstall..

but I could delete all my data, because the system is about to go live soon -> so I can't delete all my data ... sry

**Comment by jvarelmann** [comment]
hello try in the console   bin/build-storefront.sh when possible

**Comment by axe1987** [comment]
> hello try in the console bin/build-storefront.sh when possible

I did -> it also did not help

**Comment by jvarelmann** [comment]
can you provide me a link to your system please?

**Comment by axe1987** [comment]
> can you provide me a link to your system please?

It is behind a htaccess (the payone ip is whitelisted).
Let me know if you are from a different IP.

Can I somehow send you the URL in a private message?

**Comment by jvarelmann** [comment]
send the details to via mail  juergen.varelmann@payone.com

but the IP will not work we working in different networks

**Comment by axe1987** [comment]
> send the details to via mail [juergen.varelmann@payone.com](mailto:juergen.varelmann@payone.com)
> 
> but the IP will not work we working in different networks

You've got mail (with htaccess credentials)

**Comment by axe1987** [comment]
OK seems closed...
Your test couldn't reproduce the error and I wasn't able to either, after a while..

maybe it was still a caching issue

sry
