### ISSUE TITLE
No payment-status change in Shopware

### ISSUE THREAD

**Issue by fgiering** [PAYONE-GmbH/shopware-6#126]
It seems like https://github.com/PAYONE-GmbH/shopware-6/releases/tag/v2.3.0 breaks the change of the payment-status in shopware or just doesn't get the right feedback from the merchant interface.
You can place an order and pay it, but the order never changes its status to "paid".
I'm on Shopwar 6.4.2.1 and just updated the plugin in the shopware backend to 2.3.0.
Are you able to reproduce this issue?

**Comment by jvarelmann** [comment]
Hello,
did you recieve a webhook ?

**Comment by fgiering** [comment]
Yes, I got an TXID and the Status "appointed".
Doesn't matter which payone-payment method I chose, all the same.

**Comment by jvarelmann** [comment]
Hello,

please contact with this issue the Techsupport with your MID and examples , so they can investigate the issue
tech.support@payone.com

**Comment by fgiering** [comment]
😄  I contact these guys almost daily. Answers are rare.

**Comment by jvarelmann** [comment]
I´m sorry to hear this but I need the exampels and data to check whats wrong and I don´t want to publish personal datas here in the open chat

**Comment by jvarelmann** [comment]
hello,

I just installed a instance and it work like aspect for me. Please contact tech.support@payone.com with the example and MID so that we have a proper way to investigate this

**Comment by fgiering** [comment]
Pretty sure now this is a bug in the plugin. In the transaction status is an:
`<!-- ARGUMENT 1 PASSED TO PAYONEPAYMENTCOMPONENTSCURRENCYCURRENCYPRECISION:: GETROUNDEDTOTALAMOUNT() MUST BE OF THE TYPE FLOAT, STRING GIVEN, CALLED IN /APP/CUSTOM/PLUGINS/PAYONEPAYMENT/SRC/COMPONENTS/D ATAHANDLER/TRANSACTION/TRANSACTIONDATAHANDLER.PHP ON LINE 224 (500 INTERNAL SERVER ERROR) --> `

**Comment by jvarelmann** [comment]
Hello,

to the fact that you don´t want to give me the needed data to investigate this possible issue , I can only give you the advice to compare the files in your system and our plugin  
https://github.com/PAYONE-GmbH/shopware-6/blob/master/src/Components/DataHandler/Transaction/TransactionDataHandler.php

are they the same or not?

**Comment by fgiering** [comment]
I sent two mails to tech.support@payone.com. Which data do you mean?
Files are the same.

**Comment by jvarelmann** [comment]
Hello,

I could reproduce the error. it is only under special conditions. We hope to have a patch for this soon.

**Comment by fgiering** [comment]
Thank you! :)

**Comment by jvarelmann** [comment]
error resolved with new release
