### ISSUE TITLE
Error in PayoneModule 2.3.1

### ISSUE THREAD

**Issue by axe1987** [PAYONE-GmbH/shopware-6#129]
Hi.

I keep getting the following error:

`[2021-09-06T04:05:04.148661+00:00] php.CRITICAL: Uncaught Error: Argument 1 passed to PayonePayment\Components\Currency\CurrencyPrecision::getRoundedTotalAmount() must be of the type float, string given, called in /var/www/LIVE/custom/plugins/PayonePayment/src/Components/DataHandler/Transaction/TransactionDataHandler.php on line 224 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to PayonePayment\\Components\\Currency\\CurrencyPrecision::getRoundedTotalAmount() must be of the type float, string given, called in /var/www/LIVE/custom/plugins/PayonePayment/src/Components/DataHandler/Transaction/TransactionDataHandler.php on line 224 at /var/www/LIVE/custom/plugins/PayonePayment/src/Components/Currency/CurrencyPrecision.php:41)"} []
`

What can be the problem here?

Greets

**Comment by axe1987** [comment]
Ok I already opened a ticket via your support hotline.

**Comment by jvarelmann** [comment]
Hello,

we could reproduce the error. We hope to provide a fix soon

**Comment by jvarelmann** [comment]
error resolved with new release
