### ISSUE TITLE
ApplePay Error after Login in checkout

### ISSUE THREAD

**Issue by theomanus** [PAYONE-GmbH/shopware-6#138]
we have unfortunately just found out through testing that the current Payone plugin (v2.2.1) for Shopware 6.4.4.1 is buggy and the entire checkout throws an error with it. See screenshot.
![Attempted-to-load-class-Browser-from-namespace-Sinergi_BrowserDetector-Did-you-forget-a-use-statement-for-another-namespace-500-Internal-Server-Error-](https://user-images.githubusercontent.com/15118411/135857296-69bdd3ab-de44-462c-8613-a50480a11c5d.png)
As soon as a user is logged in and then goes to the shopping cart or checkout, the error is thrown. Without logging in, the shopping cart can be viewed.

**Comment by janteuber** [comment]
Hello,
our current plugin is v2.4.0
Could you please write our tech-support under tech.support@payone.de

Please describe in detail where exactly the error occurs in the checkout. It would be very helpful if you could also send a link to the test system in addition to your merchant ID.

The colleagues will then look at the case as soon as possible.

Thank you.

Regards
Jan Teuber
Product Manager Integrations

**Comment by theomanus** [comment]
Sorry I meant plugin version 2.4.0

**Comment by hreinberger** [comment]
Hi @theomanus 

Could you try the following in the shopware root folder:

```
composer require sinergi/browser-detector
bin/build-storefront.sh
bin/console cache:clear
```

That should install the needed dependency and build the storefront and caches. There may be other steps involved, depending on your deployment, so be careful.

And we should get going on a bugfix release.

**Comment by theomanus** [comment]
Yes that fixed the problem!

Thank you.
