### ISSUE TITLE
ZeroAmountCartValidator shows misleading error

### ISSUE THREAD

**Issue by Schrank** [PAYONE-GmbH/shopware-6#143]
We installed the newest version 2.4.0 which seems to not be officially released yet and get the following error:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/379680/138062299-7f256ca4-925f-4864-8c8c-3ebb5ef036a2.png">

We only use Payone Payment methods, therefore we can not change the default away from payone.

I don't understand what the purpose of `\PayonePayment\Components\CartValidator\ZeroAmountCartValidator::validate` is, but in our case it is adding this weird error message to the cart. Technically it is right, that one is not allowed to checkout with a total of 0, but the customer doesn't understand this.

The problem is, even if we have something in the cart, the error doesn't go away:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/379680/138062725-79ea57ef-1e11-4664-b540-a9c1c4038f2f.png">

For the moment I'll just remove the whole class and it's validation, but if you can tell me, that the idea behind it is, I might change my decision :-)

**Comment by FloKnapp** [comment]
I also ran in this issue and wrote a patch for it which basically checks if there are any products in the cart:
```
Index: vendor/payone-gmbh/shopware-6/src/Components/CartValidator/ZeroAmountCartValidator.php
<+>UTF-8
===================================================================
diff --git a/vendor/payone-gmbh/shopware-6/src/Components/CartValidator/ZeroAmountCartValidator.php b/vendor/payone-gmbh/shopware-6/src/Components/CartValidator/ZeroAmountCartValidator.php
--- a/vendor/payone-gmbh/shopware-6/src/Components/CartValidator/ZeroAmountCartValidator.php
+++ b/vendor/payone-gmbh/shopware-6/src/Components/CartValidator/ZeroAmountCartValidator.php	(date 1637934724463)
@@ -15,6 +15,10 @@
 {
     public function validate(Cart $cart, ErrorCollection $errors, SalesChannelContext $context): void
     {
+        if ($cart->getLineItems()->count() === 0) {
+            return;
+        }
+
         if (((int) round($cart->getPrice()->getTotalPrice() * (10 ** $context->getCurrency()->getDecimalPrecision()))) > 0) {
             return;
         }
```
