### ISSUE TITLE
The mixin "listing" is not registered

### ISSUE THREAD

**Issue by Dayjay** [PAYONE-GmbH/shopware-6#155]
I installed the latest version today via the Shopware - Admin (SW Version 6.4.7.0) and it broke our Admin, the page stays blank after login.

See screenshot for browser messages.

![grafik](https://user-images.githubusercontent.com/25659168/146085544-df6993e6-27f2-4d5f-b480-9243c34dc69b.png)

**Comment by nfsprodriver** [comment]
Same here, please remove 6.4.7.0 from the supporting list until it's fixed.

**Comment by hreinberger** [comment]
Hi, we weren't able to reproduce this yet and our compatibility testing also showed no signs of incompatibility here. Could you give us details on how exactly you did the update and from which shop version you were updating? Did you try rebuilding the admin?

We've removed compatibility with 6.4.7.0 as a precaution.

**Comment by nfsprodriver** [comment]
Thanks for the fast interaction. I Updated from 6.4.6.0 using web interface without rebuilding the admin - that never was necessary.

**Comment by Dayjay** [comment]
I installed the Payone plugin after I updated to 6.4.7.0. It was not installed prior the Shopware update. Basically a fresh installation.

**Comment by hreinberger** [comment]
Thanks for your quick replies.
The bad news: yep, you've found a bug
The good news: you should be able to mitigate this by executing `bin/build-administration.sh` via console in the shopware directory. I've tried this in two different shops, and it fixed the issue there.

We'll get going on providing a fix, though it could take until early next year.
