### ISSUE TITLE
Snippets are missing in shopware 6.4.0.0 and above

### ISSUE THREAD

**Issue by momocode-de** [PAYONE-GmbH/shopware-6#156]
We have a 6.4.3.1 Shop with the version 2.4.1 of the Payone plugin. All payone snippets are missing in the database. I think the problem is that the way you install the snippets is not working anymore since shopware 6.4.0.0. You have a folder "Resources/translations" and you install the snippets with PHP files that are tagged with "shopware.snippet.file". But this tag is not handled anymore since 6.4.0.0. You should use the auto detection like it is described here:

https://developer.shopware.com/docs/guides/plugins/plugins/storefront/add-translations#snippet-file-structure

So I think you just need to rename the "Resources/translations" directory to "Resources/snippet". That should be enough and then you can delete the PHP services.

**Comment by janteuber** [comment]
Hello @momocode-de,
I created a ticket. Our agency will check that.

**Comment by janteuber** [comment]
Hello @momocode-de ,
we already solved that and released it in our new version 3.0.0
