### ISSUE TITLE
PayPal Express checkout not working, if requireDataProtectionCheckbox is enabled

### ISSUE THREAD

**Issue by PascalPio** [PAYONE-GmbH/shopware-6#161]
If `core.loginRegistration.requireDataProtectionCheckbox` is enabled, PayPal Express Checkout is not working. The parameter `acceptedDataProtection` needs to be set but is not provided by PayPal.

**Comment by janteuber** [comment]
Hello PascalPio,

Unfortunately, i can't reproduce it. Where exactly do you activate the checkbox in the backend?

**Comment by PascalPio** [comment]
Hi,
the checkbox is located here:
Settings -> Login -> ' Data protection information must be accepted via a checkbox'

**Comment by janteuber** [comment]
Hello @PascalPio,

I checked it. The checkbox is part of the registration process, correct? Our plugin provides PPExpress only to Guests. If you are registered you can't use PPExpress.

**Comment by PascalPio** [comment]
Hi, 
that is true, but the Paypal Express Controller uses the Shopware registration route.  Therefore the `acceptedDataProtection` parameter needs to be added.

**Comment by janteuber** [comment]
Hello @PascalPio,
I got it and created a ticket for our agency.

**Comment by janteuber** [comment]
We solved that issue with https://github.com/PAYONE-GmbH/shopware-6/pull/165
