### ISSUE TITLE
Gitleaks-Action v2

### ISSUE THREAD

**Issue by zricethezav** [PAYONE-GmbH/shopware-6#182]
Hey @hreinberger @janteuber,

I maintain gitleaks and we noticed that you are not pinning your gitleaks-action version, but rather [using gitleaks-action@master](https://github.com/search?q=org%3APAYONE-GmbH+gitleaks&type=code) and wanted to give you a heads up that we are planning to merge v2 to master soon, which is a breaking update. See more details [here](https://github.com/gitleaks/gitleaks-action#-announcement). By the way, we think you'll love [v2's features](https://github.com/gitleaks/gitleaks-action#v2-benefits). Let us know if you have any questions!

**Comment by hreinberger** [comment]
Hi @zricethezav thanks for the heads up! We'll check what's needed for the upgrade and in the meantime I've pinned the version to 1.6.0
