### ISSUE TITLE
Ensure that environment variables are used correctly

### ISSUE THREAD

**Issue by Be-njamin** [PAYONE-GmbH/shopware-6#271]
The issue: https://github.com/PAYONE-GmbH/shopware-6/issues/243 still persists. Unfortunately the original issue was marked as stale and closed. Could you please have another look at this?

> The plugin uses getenv to get the environment variable. This is totally wrong and the code should inject environment variables using DI with %env(APP_URL)% as example with an default set here
> https://symfony.com/doc/current/configuration/env_var_processors.html

**Comment by janteuber** [comment]
Hello @Be-njamin ,
we solved that already in our existing 6.5 plugin
