### ISSUE TITLE
Transaction Forwarding => txactions cannot be saved

### ISSUE THREAD

**Issue by StefanDonCarne** [PAYONE-GmbH/shopware-6#273]
we´ve gone live with Plugin Version 4.2 recently and need to forward the transactions to our ERP System. 

When I try to save the txactions to be forwarded they disappear right after I click on the save button.

Steps to reproduce: 
- Add new Notification Forward
- enter URL
- enter txactions
- press save

=> url is stored, txactions stays empty

**Comment by janteuber** [comment]
Hello @StefanDonCarne ,

we fixed it in https://github.com/PAYONE-GmbH/shopware-6/pull/289/commits and will publish it in the next release.
