### ISSUE TITLE
Shopware 6.5, error activating plugin after migration of shopware 

### ISSUE THREAD

**Issue by andydandy80** [PAYONE-GmbH/shopware-6#274]
Shopware 6.5.5.2
Payone: 5.0.2
PHP: 8.2.7

I migrated shopware from 6.4.20.2 to 6.5.5.2. Then i upgraded the payone plugin to version 5.0.2.
When activating the payone plugin, the following error occurs:

```
php.CRITICAL: Uncaught Error: Class "PayonePayment\DataAbstractionLayer\Extension\PayonePaymentOrderTransactionExtension" not found {"exception":"[object
] (Error(code: 0): Class \"PayonePayment\\DataAbstractionLayer\\Extension\\PayonePaymentOrderTransactionExtension\" not found at /var/www/shopware/test/var/cache/prod_hdf33e705b
f2c89a96f784bdc50d28cd0/ContainerGPGVCuP/Shopware_Core_KernelProdContainer.php:8068)"} []

```

**Comment by jvarelmann** [comment]
Hello,

how did you do the migration ? I tried to reproduce the error but I never tried to upgrade the shopware system

LG Juergen

**Comment by jvarelmann** [comment]
How did you install the plugin via shopware or via github ?

**Comment by andydandy80** [comment]
via shopware backend

**Comment by jvarelmann** [comment]
try to deinstall, clearing the cache , and install again,

**Comment by andydandy80** [comment]
ok, that was successful, thanks a lot for your help!
