### ISSUE TITLE
Inquiry: Store-API Endpoints Support for Integrating PAYONE with Shopware 6 Headless Frontends

### ISSUE THREAD

**Issue by thomaspeissl** [PAYONE-GmbH/shopware-6#286]
Hello PAYONE Team,

I am currently exploring the integration of the PAYONE payment service provider with Shopware 6, specifically for the new headless Shopware 6 frontends as provided by https://github.com/shopware/frontends/. I'm reaching out to inquire about the compatibility and support of the PAYONE Shopware 6 plugin in this context.

Could you please confirm if the Shopware 6 plugin (found in this repository) offers the necessary Store-API endpoints that are required for a seamless integration with the headless Shopware 6 frontends? 

Additionally, if these endpoints are available, could you kindly provide some documentation or guidance on how to best implement this integration?

Thank you for your assistance and I look forward to your response.

**Comment by janteuber** [comment]
Hello @thomaspeissl ,

At the moment our plugin is not optimized or suitable for headless. However, we plan to make the adjustments in the course of the year.
