### ISSUE TITLE
Broken link to documentation in readme.md

### ISSUE THREAD

**Issue by martin-mueller-solutions** [PAYONE-GmbH/shopware-6#296]
The link in the readme.md is broken. It should link to the extensive online documentation of this plugin, but it shows a 404 page.

Link: https://docs.payone.com/display/public/INT/Shopware+6+Plugin

Location in readme.md: Line 41

**Comment by janteuber** [comment]
Hello @martin-mueller-solutions ,

Thank you very much for your advice.

We completely rebuilt our docs a few weeks ago. Therefore this link was no longer valid.

I have just changed it.
