### ISSUE TITLE
Admin: Notification Forward Detail  Page broken

### ISSUE THREAD

**Issue by hgnb99** [PAYONE-GmbH/shopware-6#304]
## Problem Description

The following routes in Admin backend show only blank page: 

```
/admin#/payone/notification/target/create
/admin#/payone/notification/target/detail/xxxxxxxxxxx
```

Browser dev console shows the following error messages: 

<img alt="Bildschirmfoto vom 2024-06-07 17-55-35" src="https://github.com/PAYONE-GmbH/shopware-6/assets/26628339/fea7fdd2-e5c9-4c4b-bf40-cf15c153c1ac" width="50%" />

[payone_notification_detail_error.log](https://github.com/user-attachments/files/15742401/payone_notification_detail_error.log)

## System Info 
Shopware 6.5.8.8
PayonePayment 6.0.0

## Possible Solution

I could fix the error by changing  the following file and re-building the administration

```
src/Resources/app/administration/src/module/payone-notification-target/page/payone-notification-target-detail/payone-notification-target-detail.html.twig
40c40
<                         <sw-card :position-identifier="payone-notification-target-detail-content"
---
>                         <sw-card position-identifier="payone-notification-target-detail-content"
```

**Comment by janteuber** [comment]
Hello @hgnb99 ,
Thank you very much.
I will forward it to our dev-Team.

**Comment by rommelfreddy** [comment]
Thank you @hgnb99 for your issue reporting. 
You are absolutely right. The colon before `position-identifier` is a typo.

We will fix this within the next release.
PR: https://github.com/PAYONE-GmbH/shopware-6/pull/315
