### ISSUE TITLE
Error PayonePaymentAmazonPayExpressButton in 6.0.1

### ISSUE THREAD

**Issue by commercewerft** [PAYONE-GmbH/shopware-6#306]
After installing 6.0.1 there will be an error: Plugin "PayonePaymentAmazonPayExpressButton" is already registered

Error: Plugin "PayonePaymentAmazonPayExpressButton" is already registered.
    at h.register (all.js?1718010068:3:17858)
    at g.register (all.js?1718010068:3:21662)
    at all.js?1718010068:8:27122
    at all.js?1718010068:8:33428
    at all.js?1718010068:8:33432

How to reproduce:
Install via composer:
`composer require store.shopware.com/payonepayment`

Then call `bin/build-storefront.sh`
After that you will find 2 versions of payone-payment.js in the file-system.

One in:
`vendor/store.shopware.com/payonepayment/src/Resources/app/storefront/dist/storefront/js/payone-payment.sh
`
One in:
`vendor/store.shopware.com/payonepayment/src/Resources/app/storefront/dist/storefront/js/payone-payment/payone-payment.sh`

Both will be included in the all.js.

If you delete the second one in
`vendor/store.shopware.com/payonepayment/src/Resources/app/storefront/dist/storefront/js/payone-payment/payone-payment.sh` and run again bin/build-storefront.sh, the error will not occur.

**Comment by janteuber** [comment]
Hello @commercewerft ,

Thank you for your message.

The problem is known in 6.0.0 and we have therefore released version 6.0.1. We have removed the 2nd file there.

**Comment by commercewerft** [comment]
Yes, but it will be created again with bin/build-storefront.sh

**Comment by commercewerft** [comment]
@janteuber so please could you reopen the ticket and test it? As described, this happens with a fresh installed 6.0.1

**Comment by hgnb99** [comment]
@janteuber ... please reopen 

having the same problem overhere: 
PayonePayment: v6.0.1
Shopware: 6.5.8.8
using shopware-cli to build assets `shopware-cli project storefront-build`

![image](https://github.com/PAYONE-GmbH/shopware-6/assets/26628339/47b34b1b-e562-4978-bb8b-18d8da5b8b86)

**Comment by nicoKraenzlein** [comment]
Hi! What's the current status of this issue. I have the same problem with the current version (v6.0.1) Shopware (6.5.8.10)
The problem comes from a wrong placed commited file:
![image](https://github.com/PAYONE-GmbH/shopware-6/assets/38782018/ee31cc2b-24c2-4333-9097-ab6b21904860)

**Comment by rommelfreddy** [comment]
if you want, you can apply the patch by composer-patches: https://github.com/PAYONE-GmbH/shopware-6/pull/316.patch
We will create a release soon.
