### ISSUE TITLE
Plugin compatible with Shopware 6.6.7.1?

### ISSUE THREAD

**Issue by VrRoempke** [PAYONE-GmbH/shopware-6#332]
Is there an info if the plugin ist fully compatible with Shopware 6.6.7.1 (and or 6.6.8.0)?

Please add this anywhere because its super critical when you update a clients shop.

**Comment by janteuber** [comment]
Hello @VrRoempke 

Thank you for your message.
Basically, our plugin has never had compatibility problems with minor versions of Shopware in the past. Of course I understand the problem itself. However, as we will not be publishing a new release for every version, we do not yet have a clever idea of how we want/should publish these adjustments.
Do you have any ideas?

**Comment by VrRoempke** [comment]
I think and hope you test the plugin with a new Shopware release. So just write something like "Tested/Compatible with SW 6.6.8.1 and lower" in the readme or at https://docs.payone.com/integration/plugins/integration-guide-shopware-6 under the Plugin Version.

**Comment by janteuber** [comment]
You can already find out which version we used for the release test in our respective release notes: https://github.com/PAYONE-GmbH/shopware-6/releases/tag/v6.1.2
I think the idea of including this in the docs is a good one. I'll implement it straight away in the next release.

**Comment by VrRoempke** [comment]
Thank you, this helps a lot 🙏🏼
