### ISSUE TITLE
Payone Decorator Conflicts with SWAG Commercial Plugin: Needs to Extend Shopware AccountOrderController

### ISSUE THREAD

**Issue by No-999** [PAYONE-GmbH/shopware-6#336]
When the SWAG Commercial Plugin and Payone are installed together, I encounter the following error:

```
Shopware\Commercial\B2B\OrderApproval\Storefront\AccountOrderControllerDecorator::__construct(): Argument #1 ($decorated) must be of type Shopware\Storefront\Controller\AccountOrderController, PayonePayment\Storefront\Controller\Account\AccountOrderControllerDecorator given, called in /app/localCache/var/cache/dev_h512f707b3a123fefeec142b66749ede4/ContainerFWnGjxV/Shopware_Core_KernelDevDebugContainer.php on line 16042
```

Actual Behavior
The error message above appears, indicating that Payone's decorator does not properly extend the required class, causing a conflict when used with the SWAG Commercial Plugin.

Expected Behavior
Payone's AccountOrderControllerDecorator should extend Shopware\Storefront\Controller\AccountOrderController to ensure compatibility with the AccountOrderControllerDecorator of the SWAG Commercial Plugin.

Steps to Reproduce
Install both the SWAG Commercial Plugin and Payone plugin.
Create a Customer
Create a Order with the Customer
Login as the Customer
Try to open the Order in ur Profile Page or perform any action that requires the use of the AccountOrderController.
The error will appear as described above.

**Comment by No-999** [comment]
The issue occurred because we had a problem with the Swag Commercial plugin, and we performed a reinstall via the CLI. This action changed the installation_at date in the database, which caused the behavior where the PayonePayment plugin installation date being earlier than the Swag Commercial plugin's resulted in an error.

Error:
PayonePayment installed_at = 2024-11-28
SwagCommercial installed_at = 2024-12-02
No Error:
PayonePayment installed_at = 2024-12-04
SwagCommercial installed_at = 2024-12-02

**Comment by rommelfreddy** [comment]
Hello @No-999 

thank you for your issue. 
we already have fixed this issue with the PR https://github.com/PAYONE-GmbH/shopware-6/pull/329. 

sadly this change hasn't released yet. I will push this to the internal. 

I will close this issue because it has been already fixed.
