### ISSUE TITLE
Recurring payment for subscriptions with credit cards

### ISSUE THREAD

**Issue by AlexBa** [PAYONE-GmbH/shopware-6#46]
Hello,

I want to ask if recurring payments with credit cards are possible in Shopware 6? 

I am developing a subscription module for Shopware 6 for my customer with Payone as the payment provider. When I look at the documentation (https://docs.payone.com/display/public/PLATFORM/Special+remarks+-+Recurring+transactions+credit+card), there are certain fields in the documentation like "recurrence" or "customer_is_present", which should also appear in your Shopware 6 plugin. But if you look at the code, these fields do not exist. In your Shopware 5 plugin they do.

Do you have more info for me? Thanks in advance!

**Comment by hreinberger** [comment]
Hi,

in Shopware 5 we supported AboCommerce as backend for creating recurring payments. Since AboCommerce won't come to Shopware 6 in the near future, we've not yet implemented any features for recurring payments. This topic is on our roadmap, but planned for "sometime later".

**Comment by AlexBa** [comment]
I have figured out, that recurring payment is working, but I have to disable 3-D Secure to make it work for credits cards

**Comment by hreinberger** [comment]
Please be advised that disabling 3D Secure won't work after Dec 31st of this year since it becomes mandatory for every issuer and acquirer. You'd need to implement our new flow using the customer_is_present and recurrence parameters after this date to successfully trigger credit card transactions by then.

**Comment by AlexBa** [comment]
Ok thank you for the info!
