### ISSUE TITLE
Typing error in translations snippet

### ISSUE THREAD

**Issue by LinoJo** [PAYONE-GmbH/shopware-6#79]
custom/plugins/PayonePayment/src/Resources/translations/de_DE/messages.de-DE.json :: 24
`"pageSubTitle": "Hier können Sie die gespeicerten Kreditkarten verwalten.",`

there is missing an `h` in `gespeicerten` should be `gespeicherten`

`"pageSubTitle": "Hier können Sie die gespeicherten Kreditkarten verwalten.",`

Please check for more errors! Thanks!

**Comment by fjbender** [comment]
Thanks for spotting the typo! I have updated the language file accordingly.
