### ISSUE TITLE
Frontend JS not loaded on checkout confirm?

### ISSUE THREAD

**Issue by apfelbox** [PAYONE-GmbH/shopware-6#84]
Hi,

I am trying out the plugin for a new shop installation – I used PAYONE before, but never in Shopware 6.
So I installed it according to your docs, but on the checkout page I just have disabled fields:

![Capture 2021-01-28_15-50-21](https://user-images.githubusercontent.com/1032411/106155052-8b8e5080-6180-11eb-98fe-352a2ba64222.png)

There is no JS that is loaded from anything related to PAYONE, so I guess this might be the problem?

I found the frontend dist file here: https://github.com/PAYONE-GmbH/shopware-6/blob/master/src/Resources/app/storefront/dist/storefront/js/payone-payment.js but it is not used anywhere in the code? Or am I missing something?

I would be really happy if you could help me, I can provide you with more details of course.

Thanks

**Comment by fjbender** [comment]
Hmm, I never experienced this issue before. Have you tried rebuilding the frontend? `./psh.phar storefront:build`

According to the Shopware [frontend plugin documentation](https://docs.shopware.com/en/shopware-platform-dev-en/how-to/js-storefront-plugin), these files should be found by Shopware automatically.

**Comment by apfelbox** [comment]
Thanks for your response!

I tried rebuilding the storefront with PSH, but unfortunately it didn't help.

I am not (yet?) incorporated in shopware internals, but your linked documentation talks about plugins in `Resources/app/storefront/src/*-plugin/*-plugin.plugin.js`.
However, this project is using a `Resources/app/storefront/src/main.js` – does that matter?

**Comment by fjbender** [comment]
For me the documentation reads

> By default the compiled js file is saved at `<plugin root>/src/Resources/app/storefront/dist/storefront/js/<plugin-name>.js`. This file will be recognized automatically by shopware.

We adhere to that schema.

I will not completely rule out that we might have a bug here, but to me this looks like more of a Shopware issue. Do other plugins' JS work?

**Comment by apfelbox** [comment]
Hello again,

you are correct, of course. The file is there in the correct place, but is there a way to debug this, why the file is still not loaded?
Everything seems fine on my side, but is there a way where I can take a look at why shopware can't find the file?


Thanks
Jannik

**Comment by fjbender** [comment]
Sorry, I'm not much of a Shopware 6 Frontend-Expert myself, so I think, you'll get better answers asking in the Shopware Community. If it turns out that we indeed have a bug in our plugin here, gladly raise this issue again :)

**Comment by apfelbox** [comment]
Rebuilding the project using `bin/build-js.sh` fixed this issue. 👍
