### ISSUE TITLE
payment error not logged

### ISSUE THREAD

**Issue by azngeek** [PAYONE-GmbH/shopware-6#90]
I have a case where i need to handle a payment for a client using his credit card for usa. It seems like that so far we have no issues with other countries so this could be something very specific.

However, my client is not able to finish the transaction as the only message he gets is:

![image](https://user-images.githubusercontent.com/213429/111751808-34aa1b00-8895-11eb-8b45-32593e754981.png)

After checking the payment logs in var/log/payone_payment_prod* and var/log/prod* in general i still was not able to identify this issue. Is there a way to have a more detailed error reporting? Maybe a hint to start debugging this would also be helpful.

**Comment by azngeek** [comment]
Can i have an update on this topic?

**Comment by p1fb** [comment]
Hey @azngeek,

sorry for the delay. We have to look into this in detail, for that please send your problem (just link this issue) as well as your merchant ID plus a time frame in which the error ocurred to tech.support@payone.com.

Hope I could help you so far, reach out to us again if you have any further questions!

Cheers,
Fabian
