### ISSUE TITLE
Credit card form template is missing in non german language

### ISSUE THREAD

**Issue by FloKnapp** [PAYONE-GmbH/shopware-6#92]
Hi,

we experienced an issue where english customers (or at least non german based shops) aren't able to see the Credit Card Form Template in the checkout process.

We are using Shopware v6.3.5.2 and the latest Payone Extension v2.1.0.

it seems that for non german customers the following detection isn't working:
```
if (!$this->isPayonePayment($context->getPaymentMethod())) {
    return;
}
```
This check can be found in ```PayonePayment\EventListener\CheckoutConfirmTemplateListener``` at line 31.

This method basically checks if the ```PaymentMethodEntity``` - as a result from ```$context->getPaymentMethod()``` - contains a CustomField with the key ```payone_payment```. This result is empty for the English version in our Project, but filled for the German version. Therefore the Template isn't shown, which prevents customers from adding their card data.

Can you confirm this issue and do you maybe have a quick solution for this problem?

Thank you in advance!

**Comment by hreinberger** [comment]
Hi @FloKnapp 
we're aware of an issue where custom fields only show up in German and English Sales Channels. This is due to architectural challenges we faced in the early days of Shopware 6. We're working on refacturing big parts of the plugin, which should deal with these kinds of technical debt. I hope we can bring this in Q2, but I don't have a specific date for it yet.

**Comment by FloKnapp** [comment]
Hi @hreinberger,

thank you for your quick response.

Unfortunately we are experiencing this issue also on our English Sales Channel. Currently only the German Sales Channel is able to display the Credit Card Form based on the condition whether the CustomField `payone_payment` exists or not. I build a workaround which adds the required CustomFields when:
- there aren't any fields present
- the credit card from Payone is selected

This should fix our issue temporarily but i'd be happy to hear about this getting resolved in a more professional way. ;-)

Thank you again for the clarification!
