### ISSUE TITLE
Support for Shopware 6.4 | PHP8

### ISSUE THREAD

**Issue by felixgoldstein** [PAYONE-GmbH/shopware-6#93]
Plugin is relying on constants that don't exists anymore, for example `Shopware\Core\System\StateMachine\Aggregation\StateMachineTransition\StateMachineTransitionActions::ACTION_PAY_PARTIALLY`

**Comment by hreinberger** [comment]
yep, we're aware of that and working on it. Sadly, we won't be compatible in time for the 6.4 launch 😐

**Comment by patchee500** [comment]
@hreinberger do you have a rough idea when we can expect 6.4 compatibility?

**Comment by areanet-doschmid** [comment]
@hreinberger we also need the plugin for a Shopware 6.4 installation. When will there be a release for the plugin?

**Comment by hreinberger** [comment]
Hi all, #97 will add the 6.4 compatibility. We're now running extensive end-to-end tests on this and hope we can at least tag a beta release this week.

**Comment by hreinberger** [comment]
Hi everyone, we've just tagged a beta release with support for Shopware 6.4: https://github.com/PAYONE-GmbH/shopware-6/releases/tag/v2.2.0-beta.1 We've tested with PHP 7.4, but I think there are only minor dependency issues for PHP 8 support.

**Comment by aa-matthias** [comment]
@hreinberger the plugin (v2.2.0) cannot be installed in Shopware 6.4 when running on PHP 8 because of:

https://github.com/PAYONE-GmbH/shopware-6/blob/master/composer.json#L23
